name: ncov-ab-escape
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - augur
  - pandas
  - seaborn
  - notebook
  - natsort
  - click
  - pip
  - openpyxl
  - pip:
      - dmslogo
      - scikit-learn
      - polyclonal
